### ISSUE TITLE
Malicious code in commit

### ISSUE THREAD

**Issue by dalu** [SWG-Source/src#5]
https://github.com/SWG-Source/src/commit/7a9d070608f5063715d668787bec5b66b8da04c7

This WebAPI doesn't seem to be present anymore but it was included unless it was build with `-DSTELLA_INTERNAL` as far as I can see.

I'm opening this issue because this @Cekis person claims the opposite, which can be clearly seen as a lie.

I would advise anyone cloning this repository to pay special attention. More malicious code could be present and obfuscated so a simple search won't show it. I have not done such a search.

The fact that this person is trying to hide it and has locked discussion for collaborators only shows that this even might have more backdoors and should be treated very carefully.

Distributing viruses and backdoors is a crime.

Should this issue be deleted I will report this repository to github for spreading malicious code and also the US authorities.

**Comment by Tekaoh** [comment]
I might point out that this commit is three years old and doesn't reflect the state of CMakeLists.txt in its current form.

I actually don't understand the accusation you're attempting to make. If there's something wrong with the code in its current form, please feel free to provide a detailed explanation and we can have a conversation about it.

**Comment by Tekaoh** [comment]
Feel free to hop into our discord and we can chat https://discord.gg/Va8e6n8

**Comment by Tekaoh** [comment]
After discussion on Discord, it seems like the code in question is a failsafe from when Stella Bellum was a closed project. It was a protection against internal VMs being leaked. A call from stellabellum.net could run `rm -rf` and wreck the VM. But the code is now open and webAPIHeartbeat.cpp is no longer present in the repository. There is now either webAPI or jsonWebAPI. The only way you might be at risk to this vulnerability is if you were to compile an old git tree, which you shouldn't do. There's nothing we can do about code in the git history besides deleting it all, which is dumb. I'm therefore closing this issue because it's not relevant to current code.  I'll leave the issue undeleted to preserve a record of the accusation as well as the explanation.

**Comment by Cekis** [comment]
Simply because code has a `rm -rf` does not mean it is malicious.  It means it is removing a directory recursively.  If the directory it is removing is within the confines of the system then your accusation and threats of reporting are simply unfounded.

If you must know the purpose of the `rm -rf`, then that is fine, I will second @Tekaoh 's response that the code in question was a failsafe to remove any binaries that were a result from this code (nothing more unless somebody mistakenly put something in a child directory that stems from this project structure) should they be installed, compiled, copied, etc. from the original proprietors of this code.  You may not have interest in this project, but I think you need to understand more about what it is and where it came from before simply declaring malicious coding.

Personally, I see where you are coming from and I would suspect you did some sort of search to find the `rm -rf`.  Unfortunately, I believe you don't have any context of why it's there or how it's used and probably don't know much about this project in general.  I can tell you it's not malicious and its purpose is historical and there is no threat that is malicious in nature as this is not a common shared application that gets randomly installed or stored on an unsuspecting user's system.

It's just simply a blanket removal of items resulting from this project and nothing more than that.  Not harmless, but equally not malicious in nature either.  It's meant for cleanup purposes only.

**Comment by Cekis** [comment]
Regarding my conversation lock - I did so because we've heard that function was considered malicious before.  I locked the conversation because we have already had this same argument with other users.  As a result, changes were put in that required somebody to allow the removal if they wanted as opposed to allowing the removal without consent.
